#cloud-config
packages:
  - fail2ban
  - ufw
  - curl
  - htop
  - nano
  - git
  - nmap
  - nfs-common
  - wget
package_update: true
package_upgrade: true
write_files:
  - path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT] 
      ignoreip = 127.0.0.1/32
      bantime  = 3600
      findtime  = 300
      maxretry = 3
      banaction = iptables-multiport
      backend = auto
      [sshd] 
      enabled = true
    append: false
runcmd:
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22
  - echo y | ufw enable
  - systemctl enable fail2ban
  - systemctl restart fail2ban
